apiVersion: v1
kind: ConfigMap
metadata:
  name: adot-collector-config
  namespace: shop-prod
data:
  collector.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317

    processors:
      batch:
        timeout: 1s
        send_batch_size: 64

    exporters:
      awsxray:
        region: us-east-1
        indexed_attributes: [service.name, http.status_code]
      debug:
        verbosity: normal

    service:
      telemetry:
        logs:
          level: info
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [awsxray, debug]
